name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io
      - name: Build Docker image
        run: docker build -f Dockerfile.production -t estebansilvac/break-point-backend .
      - name: Publich image to Docker Hub
        run: docker push estebansilvac/break-point-backend:latest
    env: # Or as an environment variable
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATRABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      URL_FRONTEND: ${{ secrets.URL_FRONTEND }}
      PORT: ${{ secrets.PORT }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull estebansilvac/break-point-backend:latest
      - name: Delete old container
        run: docker rm -f break-point-backend-container
      - name: Variables? 
        run: echo ${{ secrets.DATABASE_HOST }} $DATABASE_PORT ${{ secrets.DATABASE_NAME }} ${{ secrets.DATABASE_USERNAME }} ${{ secrets.DATABASE_PASSWORD }} ${{ secrets.JWT_SECRET }} ${{ secrets.URL_FRONTEND }} ${{ secrets.PORT }} 
      - name: Run new container
        run: docker run -d -p 3001:3001 --name break-point-backend-container estebansilvac/break-point-backend
